#VIEWS##################
salon_view:
  view: yes
  name: Salon
  entities:
    - group.salon

kuchnia_view:
  view: yes
  name: Kuchnia
  entities:
    - group.kuchnia

bable_view:
  view: yes
  name: Bąble
  entities:
    - group.bable

hubert_view:
  view: yes
  name: Hubert
  entities:
    - group.hubert

dom_view:
  view: yes
  name: Dom
  entities:
    - group.dom

pogoda_view:
  view: yes
  name: Pogoda
  icon: mdi:weather-partlycloudy
  entities:
    - group.pogoda
    - group.prognoza
    - group.czujniki

ogrzewanie_view:
  view: yes
  name: Ogrzewanie
  icon: mdi:radiator
  entities:
    - group.ogrzewanie
    - group.temp_salon
    - group.czas_salon
    - group.temp_kuchnia
    - group.czas_kuchnia
    - group.temp_bable
    - group.czas_bable
    - group.temp_hubert
    - group.czas_hubert
#GROUPS#################
salon:
  name: Salon
  entities:
    - binary_sensor.kontaktron_mysv20_4_0
    - sensor.temphumbaro_mys_20_9_0
    - sensor.temphumbaro_mys_20_9_2
    - binary_sensor.switch_158d0001b18482

kuchnia:
  name: Kuchnia
  entities:
    - binary_sensor.kontaktron_mysv20_2_0
    - binary_sensor.kontaktron_mysv20_6_0
    - sensor.temphum_mys_20_1_0
    - sensor.temphum_mys_20_1_1
    - light.dimmer_i_pir_mys_20_8_0
    - binary_sensor.dimmer_i_pir_mys_20_8_1
    - binary_sensor.switch_158d00018b42ce

bable:
  name: Bąble
  entities:
    - binary_sensor.kontaktron_mysv20_7_0
    - sensor.temphum_mys_20_10_0
    - sensor.temphum_mys_20_10_1
    - sensor.illumination_34ce008d6d9c

hubert:
  name: Hubert
  entities:
    - binary_sensor.kontaktron_mysv20_5_0
    - sensor.temphum_mys_20_12_1
    - sensor.temphum_mys_20_12_0

dom:
  name: Dom
  entities:
    - binary_sensor.door_window_sensor_158d0001d85dbe
    - binary_sensor.door_window_sensor_158d00019fe6e4

#WunderGround
prognoza:
  name: Prognoza
  entities:
    - sensor.pws_weather_2d_metric
    - sensor.pws_weather_2n_metric
    - sensor.pws_weather_3d_metric
    - sensor.pws_weather_3n_metric
    
pogoda:
  name: Aktualna pogoda - Wunderground
  entities:
    - sun.sun
    - sensor.pws_temp_c
    - sensor.pws_feelslike_c
    - sensor.pws_weather
    - sensor.pws_weather_1d_metric
    - sensor.pws_weather_1n_metric

czujniki:
  name: Czujniki
  entities:
    - sensor.temperature_158d0001d36d02
    - sensor.humidity_158d0001d36d02
    - sensor.pressure_158d0001d36d02
    - sensor.temphum_mys_20_11_1
    - sensor.temphum_mys_20_11_0


#aktualna_pogoda:
#  name: Aktualna Pogoda
#  entities:
#    - sensor.pws_weather_1d_metric
#    - sensor.pws_temp_high_record_c
#    - sensor.pws_temp_high_1d_c
#    - sensor.pws_temp_c
#    - sensor.pws_temp_low_1d_c
#    - sensor.pws_temp_low_record_c
#    - sensor.pws_precip_1d
#    - sensor.pws_precip_1d_mm
#    - sensor.pws_wind_kph
#    - sensor.pws_wind_1d_kph
#    - sensor.pws_alerts

ogrzewanie:
  name: Ogrzewanie
  entities:
    - input_select.ogrzewanie_dom
    - input_select.ogrzewanie_salon
    - input_select.ogrzewanie_kuchnia
    - input_select.ogrzewanie_bable
    - input_select.ogrzewanie_hubert

temp_salon:
  name: Temperatury dla Salonu
  entities:
    - input_number.temp_salon_wirt
    - input_number.temp_salon_akt
    - input_number.temp_salon_rano
    - input_number.temp_salon_praca
    - input_number.temp_salon_dzien
    - input_number.temp_salon_noc

temp_kuchnia:
  name: Temperatury dla Kuchni
  entities:
    - input_number.temp_kuchnia_wirt
    - input_number.temp_kuchnia_akt
    - input_number.temp_kuchnia_rano
    - input_number.temp_kuchnia_praca
    - input_number.temp_kuchnia_dzien
    - input_number.temp_kuchnia_noc
temp_bable:
  name: Temperatury dla Bąbli
  entities:
    - input_number.temp_bable_wirt
    - input_number.temp_bable_akt
    - input_number.temp_bable_rano
    - input_number.temp_bable_praca
    - input_number.temp_bable_dzien
    - input_number.temp_bable_noc

temp_hubert:
  name: Temperatury dla Huberta
  entities:
    - input_number.temp_hubert_wirt
    - input_number.temp_hubert_akt
    - input_number.temp_hubert_rano
    - input_number.temp_hubert_praca
    - input_number.temp_hubert_dzien
    - input_number.temp_hubert_noc

czas_salon:
  name: Czasy dla Salonu
  entities:
    - input_datetime.czas_salon_rano
    - input_datetime.czas_salon_praca
    - input_datetime.czas_salon_dzien
    - input_datetime.czas_salon_noc

czas_kuchnia:
  name: Czasy dla Kuchni
  entities:
    - input_datetime.czas_kuchnia_rano
    - input_datetime.czas_kuchnia_praca
    - input_datetime.czas_kuchnia_dzien
    - input_datetime.czas_kuchnia_noc

czas_bable:
  name: Czasy dla Bąbli
  entities:
    - input_datetime.czas_bable_rano
    - input_datetime.czas_bable_praca
    - input_datetime.czas_bable_dzien
    - input_datetime.czas_bable_noc

czas_hubert:
  name: Czasy dla Huberta
  entities:
    - input_datetime.czas_hubert_rano
    - input_datetime.czas_hubert_praca
    - input_datetime.czas_hubert_dzien
    - input_datetime.czas_hubert_noc
